version: 2.1

jobs:
  conda_linux64_test:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            sudo apt-get install build-essential cmake
            bash .circleci/test.conda.recipe/build.sh

# TODO: Make recipe dynamically according to current git_rev / SHA1.
#            export git_rev=$CIRCLE_SHA1

#  conda_linux64_release:
#    docker:
#      - image: deepgenomics/conda
#    steps:
#      - checkout
#      - run:
#          name: Build and test
#          command: bash .circleci/test.conda.recipe/build.sh
# TODO: Make recipe dynamically according to current git_rev / SHA1.
#            export git_rev=$CIRCLE_SHA1

#  conda_linux32_test:
#  conda_linux32_release:
#  conda_osx64_test:
#  conda_osx64_release:
#  conda_osx32_test:
#  conda_osx32_release:
#  conda_win32_test:
#  conda_win32_release:
#  conda_win64_test:
#  conda_win64_release:


#  macosx_xcode_11_release:
#    macos:
#      xcode: "11.3.0"
#    steps:
#      - checkout
#      - run:
#          name: Build and test
#          command: >-
#            git submodule update --init --recursive &&
#            bash ./tools/circleci_macosx_xcode_11_release.sh

workflows:
  version: 2.1
  all_builds:
    jobs:
      - conda_linux64_test
