{% set name = "tudatpy" %}

package:
  name: {{ name }}
  version: {{ environ.get('NEW_GIT_TAG', 'dev') }}

source:
  git_url: ../

build:
  # A non-negative integer representing the build number of the package.
  #  Unlike the build string, the build_number is inspected by conda.
  #  Conda uses it to sort packages that have otherwise identical names
  #  and versions to determine the latest one. This is important because
  #  new builds that contain bug fixes for the way a package is built may be
  #  added to a repository.
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('c') }}              # [not win]
    - vs2017_{{ target_platform  }}    # [win]
    - cmake

outputs:
  - name: {{ name }}
    run_exports:
      - {{ pin_compatible('tudat', max_pin='x.x') }}
      - {{ pin_compatible('tudat-cspice', max_pin='x.x') }}
      - {{ pin_compatible('tudat-sofa', max_pin='x.x') }}
      - {{ pin_compatible('numpy', max_pin='x.x') }}
    requirements:
      build:
        # Tools required to build the package. These packages are run on the build
        # system and include things such as revision control systems (Git, SVN) make
        # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
        # or native when not cross-compiling), and any source pre-processors.
        - eigen
        - tudat-cspice
        - tudat-sofa
        - tudat
      host:
        # Packages that need to be specific to the target platform when the
        # target platform is not necessarily the same as the native build
        # platform
        - tudat
        - tudat-cspice
        - tudat-sofa
        - python
        - eigen
        - numpy
      run:
        # Packages required to run the package. These are the dependencies
        # that are installed automatically whenever the package is installed.
        # Package names should follow the package match specifications.
        - {{ pin_compatible('numpy') }}
        - {{ pin_compatible('tudat') }}
        - python

test:
  requires:
    - pytest
  files:
    - test.py
    - tests/test_constants.py
    - tests/test_interface_spice.py

about:
  home: http://tudat.tudelft.nl/
  license: BSD
  license_family: BSD
  summary: Tudat Bundle packs Tudat and external libraries in a modular fashion
