name: tudatpy-docs
channels:
  - conda-forge
  - tudat-team
dependencies:
  # All standard tudat-bundle deps are needed for sphinx-documentation for tudatpy.
  - python=3.8
  - numpy
  - tudatpy
  - pytest
  - matplotlib # for tudat.plotting
  - basemap # for tudat.plotting
  # Other doc related
  - jinja2
  - yaml
  - pydantic
  - numpydoc
  - pip
  - pip:
     - nbsphinx
     - sphinx_rtd_theme
     - sphinxcontrib-fulltoc
     - sphinxcontrib-bibtex